# Specify either a game or a speedrun.com username
game: ""
username: ""

# Not necessary if you're downloading from a username
app-id: <your app id>
app-secret: <your app secret>

# Where to store the videos
video-folder-name: videos

# Whether to download the videos or just look at the output
download-videos: true

# For games, whether to download all videos irregardless of whether or not the channel has exceeded the 100 hour highlight limit
allow-all: false
